### ISSUE TITLE
关于用对象更新时

### ISSUE THREAD

**Issue by NumFive5** [mouzt/mzt-biz-log#108]
![image](https://user-images.githubusercontent.com/46628642/202416002-5227a66b-8387-46e9-8d67-9b9ac753d782.png)
是否可以考虑除了拼接文案外,将更新的字段属性名,名字,值,作为collection放入LogRecordOps对象中

**Comment by mouzt** [comment]
是要通过扩展点自己解析 LogRecordOps 然后存储吗？
