### ISSUE TITLE
@DiffLogField在LocalDateTime类型的字段上无效

### ISSUE THREAD

**Issue by xx0410** [mouzt/mzt-biz-log#114]
<img width="855" alt="截屏2022-12-16 12 40 53" src="https://user-images.githubusercontent.com/48743761/208023740-16d8d9a4-9fee-4e4d-bf48-4942161f0bc0.png">
node.getValueTypeInfo()被return掉了

**Comment by wulangcode** [comment]
#111 ，pr #112

**Comment by mouzt** [comment]
3.0.4 版本已经修复
