### ISSUE TITLE
mzt.log.record.diffLog设置为true后，日志格式不正确

### ISSUE THREAD

**Issue by rigganwang** [mouzt/mzt-biz-log#128]
场景：
1. 用户对某个业务对象执行更新操作，变更了部分属性
2. 该属性不属于对象的核心业务属性，例如，备注等，所以未设置@DiffLogField

期望：
使用_DIFF函数时，若未发生变化，能输出其他日志内容，如”更新了XXX对象“

**Comment by rigganwang** [comment]
更新了订单，{_DIFF{#command}}

**Comment by wulangcode** [comment]
没太懂你期望的输出。

**Comment by wulangcode** [comment]
如果你不希望记录，用`DIffLogIgnore`可以吗？
