### ISSUE TITLE
如何解决service多个方法打印日志不成功的问题

### ISSUE THREAD

**Issue by huangtaoz** [mouzt/mzt-biz-log#143]
`@Service`
`public class Demo {`
`    @LogRecord(success="step a"...)`
`    public void A() {`
`       ......`
`       B();`
`    }`
`  @LogRecord(success="step b"...)`
`  public void B() {`
  `   ......`
`  }`
`}`
我在调用A方法的时候，如何能使B方法的LogRecord生效。（除了在类中注入Demo的bean,然后在A方法中通过demo.B()方法）

**Comment by wulangcode** [comment]
参考事物失效的解决方法

**Comment by ggfickle** [comment]
使用AopContext.currentProxy()来解决

**Comment by mouzt** [comment]
参考上面两个同学建议
