### ISSUE TITLE
当描述中存在多个变量时，_DIFF 无差异也会记录日志

### ISSUE THREAD

**Issue by Soul-debug** [mouzt/mzt-biz-log#153]
文档提到
![38bb6284ebdb3f3c52152507a21dea8](https://github.com/mouzt/mzt-biz-log/assets/61300224/78e71328-48f0-4d9c-a776-e4ad0b94ad6e)
可是当我的①处有一个提示变量，②处对比无差异，还是一样的记录了日志
![eb37451167e88fd94247c136768cafc](https://github.com/mouzt/mzt-biz-log/assets/61300224/593d4f93-5cf6-47af-a5cd-a70403352bcb)
我看源码是因为这个提示变量导致
![cbf0d726422826a7f95f0880345650e](https://github.com/mouzt/mzt-biz-log/assets/61300224/db193ff1-c2ac-4906-9b01-63813c58d940)
走进了这里，导致
![883b63704e274a47301f72659f902fa](https://github.com/mouzt/mzt-biz-log/assets/61300224/c02a4a1a-414d-4aed-a44b-18ff9733448e)
这里没有进，就记录了一个空的日志
如何能让它不记录日志呢？

**Comment by mouzt** [comment]
will fix in 3.0.5

**Comment by mouzt** [comment]
3.0.7-snapshot 已经修复，可运行单测：test_sameDiffNotRecord 和 test_sameDiffNotRecordWithMoreExpression 验证
