### ISSUE TITLE
@LogRecord注解嵌套的问题

### ISSUE THREAD

**Issue by vens-cy** [mouzt/mzt-biz-log#168]
假设我在service里面有一个A(), A里面会调用API访问B()，在A()和B()的上面都加了注解@LogRecord，这两个注解只会生效一个，有时候是B上面的生效，有时候是A上面的生效。有没有什么办法让两个都生效呢？

**Comment by uliian** [comment]
你的A、B方法是不是都在同一个class里？

**Comment by Justin-Binber** [comment]
TextServiceImpl textServiceProxy = applicationContext.getBean(TextServiceImpl.class);
            return textServiceProxy.createAuditText(createReqVO);

**Comment by mouzt** [comment]
参考 spring transaction 设计
