### ISSUE TITLE
 建议：@ LogRecordAnnotation里只有函数放到整体方法执行之前执行，适应以下场景

### ISSUE THREAD

**Issue by miaoyinjun** [mouzt/mzt-biz-log#17]
1. 物理删除场景，参数只有用户id，在函数里先查出被删除用户的用户账号，记录哪些账号被删除。
2. 修改场景，在函数里先根据id查找被修改用户之前的信息，在对修改入参对比，最后返回字段：新值，旧值。

这样就不用在方法里**删除/修改**前，先使用LogRecordContext进行查询赋值了，或者作者有考虑请告知，谢谢。

**Comment by mouzt** [comment]
嗯，确实有这样的场景
之前考虑过加一个配置，让日志的解析即可以在方法之前也可以在方法之后执行，后面考虑支持下

如果想使用「新值，旧值」 可以通过 LogRecordContext（1.0.4版本支持的），在方法执行之前 put 一下「旧值」实现，函数中可以访问这个旧值。

就是实现起来逻辑有些耦合了，不是很优雅。哈哈

**Comment by mouzt** [comment]
DDL：2021-08-08

**Comment by mouzt** [comment]
1.0.6 版本已经支持

**Comment by mouzt** [comment]
> 好像没有看到相关这个问题的解决方式，能提示一下么？

自定义函数有个 executeBefore 为true的时候，代表自定义函数会在方法运行之前执行
