### ISSUE TITLE
@LogRecordAnnotation 这个注解只能在接口的实现方法上才有作用

### ISSUE THREAD

**Issue by lorkoy** [mouzt/mzt-biz-log#21]
如题
不是接口的实现方法不能记录日志吗？例如
@Override
public void A(){//接口中定义的方法
 if(){
 B();
 }else{
  C();
}
}
@LogRecordAnnotation
public void B(){}

@LogRecordAnnotation
public void C(){}

具体的业务在B和C方法中(B和C不是接口中定义的方法)，目前注解配置在B和C方法上，没有打印日志，还是我姿势不对？

**Comment by mouzt** [comment]
同一个类中调用不会走到Spring的代理，Spring aop 会失效，把 B() 和 C() 移到另一个类中，或者在本类中注入一下 self，通过self.B() 调用可以生效

**Comment by mouzt** [comment]
可以看下Spring AOP 方面的知识哦

**Comment by lorkoy** [comment]
> 可以看下Spring AOP 方面的知识哦

好的 谢啦，以为只要加了注解的方法都能调用呢

**Comment by smnjj44** [comment]
> 同一个类中调用不会走到Spring的代理，Spring aop 会失效，把 B() 和 C() 移到另一个类中，或者在本类中注入一下 self，通过self.B() 调用可以生效

AopContext.currentProxy()这样好像可以调用到本类的aop方法

**Comment by mouzt** [comment]
> > 同一个类中调用不会走到Spring的代理，Spring aop 会失效，把 B() 和 C() 移到另一个类中，或者在本类中注入一下 self，通过self.B() 调用可以生效
> 
> AopContext.currentProxy()这样好像可以调用到本类的aop方法

可以的，强转一下
