### ISSUE TITLE
还在维护吗？考虑日志异步处理吗？

### ISSUE THREAD

**Issue by beichenhpy** [mouzt/mzt-biz-log#23]
您好，我看到具体的逻辑`Interceptor`那里的record方法还是同步的，有考虑异步处理吗？

**Comment by mouzt** [comment]
还在维护呢
因为日志的解析都是内存操作，所以耗时的瓶颈大部分在保存的方法，可以继承 ILogRecordService 实现类把 record 方法设置成异步，可以满足你需求吗？

**Comment by beichenhpy** [comment]
> 还在维护呢
> 因为日志的解析都是内存操作，所以耗时的瓶颈大部分在保存的方法，可以继承 ILogRecordService 实现类把 record 方法设置成异步，可以满足你需求吗？

好的，感谢大佬回复
