### ISSUE TITLE
日志结果记录状态值

### ISSUE THREAD

**Issue by ScarletDrop** [mouzt/mzt-biz-log#25]
可以根据 success 和 fail 记录一下操作状态，或者留一个扩展接口，开发者根据业务自行设置状态

**Comment by mouzt** [comment]
可以的，安排

**Comment by mouzt** [comment]
DDL：2021-08-08

**Comment by mouzt** [comment]
1.1.0-SNAPSHOT 版本已经修复，稳定后发release
