### ISSUE TITLE
请问如何记录方法请求时长

### ISSUE THREAD

**Issue by fleshmen** [mouzt/mzt-biz-log#26]
请问在哪里可以设置添加记录方法的请求时长

**Comment by mouzt** [comment]
记录打日志的时长吗？

**Comment by fleshmen** [comment]
是从请求方法到日志插入数据库完成的时间，比如某个接口，我需要记录请求花了多少时间


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mouzt/mzt-biz-log"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月20日(星期二) 下午5:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mouzt/mzt-biz-log] 请问如何记录方法请求时长 (#26)





 
记录打日志的时长吗？

**Comment by mouzt** [comment]
这块打算加个回调函数，让业务实现打点

**Comment by mouzt** [comment]
DDL：2021-08-08

**Comment by mouzt** [comment]
这块想了下，可以通过自定义 AOP 拦截实现，没有必要加回调函数，你看看，如果还有问题加我微信联系我
