### ISSUE TITLE
操作日志是否支持心中自定义字段。

### ISSUE THREAD

**Issue by zhangyungen** [mouzt/mzt-biz-log#31]
有些操作日志，有多个状态，某些情况要根据这些状态进行操作日志过滤，比如  ，申请中，审核不通过，审核通过，反审不通过，多个状态来回跳转情况，操作日志有多条，此时就是想看通过或者不通过的。这种需求。

**Comment by mouzt** [comment]
LogRecordAnnotation 注解上的 category 字段可以满足你的要求吗？

**Comment by zhangyungen** [comment]
cateory，大部分情况会被占用，因为操作日志，要区分操作来源领域：是管理后端，还是C端，还是合作商家端等情况。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月27日(星期一) 中午11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mouzt/mzt-biz-log] 操作日志是否支持心中自定义字段。 (#31)





 
LogRecordAnnotation 注解上的 category 字段可以满足你的要求吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mouzt** [comment]
嗯，可以考虑加个 extra 字段，让业务自己扩展

**Comment by mouzt** [comment]
extra 可用
