### ISSUE TITLE
操作日志，能否增加增加功能字段

### ISSUE THREAD

**Issue by zhangyungen** [mouzt/mzt-biz-log#32]
操作日志分类，一般是都有： 系统（租户）、模块、功能（新增，修改，下单，删除，审核，记录等），操作者角色，主业务单号。老师，是否能增加操作功能字段呢？

**Comment by mouzt** [comment]
category 可以吗？

**Comment by huxudong** [comment]
理解他的需求应该是这样，加一个operate字段
tenant（系统）、category（模块）、operate（操作：新增、审核等）

只用category实现也可以 category-add 、category-update... 查询日志的时候like 'categroy%'

**Comment by mouzt** [comment]
嗯，是可以的
