### ISSUE TITLE
{{#orderId}}表达式是否有必要精简？

### ISSUE THREAD

**Issue by boosan** [mouzt/mzt-biz-log#33]
如题，
如果就只有放个变量的需求表达式这么写{#orderId}就够了，需要调用函数时{ORDER{#orderId}}写两个括号。
单括号会更简洁一点

**Comment by mouzt** [comment]
嗯，你说的方式是可以的。

**Comment by boosan** [comment]
谢谢你的回答！
就是说未来的版本表达式精简会支持上？

**Comment by mouzt** [comment]
嗯 会的。

**Comment by mouzt** [comment]
目前考虑两个原因暂不修复
1.  单个括号和用户的标识重复概率比较大
2. 对历史用户有影响
