### ISSUE TITLE
日志记录实体ID类型

### ISSUE THREAD

**Issue by MentosL** [mouzt/mzt-biz-log#38]
背景：
目前想在部分业务上使用该组件，数据存储想使用es进行存储。发现在写入的时候对应LOG实体id为int类型，业务中目前id生成策略为Long和String，强制int类型有点不满足当下。

需求：
想要业务自行定义类型

**Comment by mouzt** [comment]
好的哇，欢迎PR

**Comment by mouzt** [comment]
Log实体改为了 Serializable 类型
