### ISSUE TITLE
启动类的注解“@EnableTransactionManagement” 作用

### ISSUE THREAD

**Issue by vastpn** [mouzt/mzt-biz-log#41]
感谢楼主提供日志框架设计方法。研究了代码，发现有部分不是很清楚，请帮忙回复下

1、为什么Demo项目中，必须要在启动类中加入 @EnableTransactionManagement 注解，其作用是什么？

2、 当去掉 @EnableTransactionManagement 注解后，日志功能就不正常了

**Comment by mouzt** [comment]
去掉后可以的，是不是别的地方搞错了

**Comment by vastpn** [comment]
跟踪启动和堆栈信息，去掉 @EnableTransactionManagement 没有走代理。原因是“EnableLogRecord ”注解中没有 proxyTargetClass 属性，增加此属性可以正常处理  动态代理及Cglib 代理的方法日志。

**Comment by mouzt** [comment]
1.1.0-SNAPSHOT 版本已经修复，稳定后发release
