### ISSUE TITLE
表达式嵌套问题

### ISSUE THREAD

**Issue by imyzt** [mouzt/mzt-biz-log#43]
您好，请问后续是否考虑支持表达式嵌套，类似于 `{{#dto.id != null ? '更新{{#dto.title}}' : '创建'}}了xxx业务「{{#dto.title}}」`

**Comment by mouzt** [comment]
嗯 在后续规划里面

**Comment by mouzt** [comment]
1.1.0-SNAPSHOT 版本已经修复，稳定后发release
