### ISSUE TITLE
是参考的美团的文章写的么

### ISSUE THREAD

**Issue by dbj-dxy** [mouzt/mzt-biz-log#49]
https://tech.meituan.com/2021/09/16/operational-logbook.html

**Comment by mouzt** [comment]
哈哈，文章作者正是本人

**Comment by dbj-dxy** [comment]
> 哈哈，文章作者正是本人

哈哈，大佬，我还想这人copy了也不标注一下原文链接

**Comment by mouzt** [comment]
😁😁
