### ISSUE TITLE
LogRecordValueParser中关于前置函数计算和匹配的问题

### ISSUE THREAD

**Issue by qugemingzizhemefeijin** [mouzt/mzt-biz-log#50]
<pre>
LogRecordValueParser 类

if (logFunctionParser.beforeFunction(functionName)) {
	Object value = expressionEvaluator.parseExpression(expression, annotatedElementKey, evaluationContext);
	String functionReturnValue = logFunctionParser.getFunctionReturnValue(null, value, functionName);
	// 这里getFunctionCallInstanceKey传入的值为express是不是更好一些？如果value字段的值被改变过后，可能会造成functionNameAndReturnValueMap匹配不到数据
	String functionCallInstanceKey = logFunctionParser.getFunctionCallInstanceKey(functionName, value);
	functionNameAndReturnValueMap.put(functionCallInstanceKey, functionReturnValue);
}
</pre>

**Comment by mouzt** [comment]
我修复下的

**Comment by mouzt** [comment]
最新版本已修复
