### ISSUE TITLE
LogFunctionParser 优化建议

### ISSUE THREAD

**Issue by FitzzZOwO** [mouzt/mzt-biz-log#55]
com.mzt.logapi.starter.support.parse.LogFunctionParser#getFunctionReturnValue 第21行会导致NPE问题，希望能优化一下。

场景是心跳请求无参数，导致了NPE。

**Comment by FitzzZOwO** [comment]
![image](https://user-images.githubusercontent.com/65837747/157605749-03448c54-0f4a-44b0-80e2-9630eaf94bdd.png)

**Comment by mouzt** [comment]
收到，马上修复

**Comment by mouzt** [comment]
2.0.2 修复
