### ISSUE TITLE
LogRecordContext能否支持跨方法的全局变量

### ISSUE THREAD

**Issue by huntkalio** [mouzt/mzt-biz-log#56]
LogRecordContext 设置的变量当前只支持在方法内使用，跨方法变量访问不了；能否增加putGlobalVariable

**Comment by mouzt** [comment]
可以的

**Comment by huntkalio** [comment]
嗯，可以新增个全局变量的map，clear 方法里stack出栈后判断stack是否为空，为空则清空全局的map。
另外一个问题，sdk里可以配置打印切点所在文件及其行数（方便定位问题）么

**Comment by mouzt** [comment]
加个debug日志可以嘛，用户可以通过配置显示打开关闭

**Comment by mouzt** [comment]
3.0.2 已支持
