### ISSUE TITLE
LogFunctionParser.java#L21  value可能为null（变量未取到值），需增加value是否为空判断

### ISSUE THREAD

**Issue by huntkalio** [mouzt/mzt-biz-log#57]
https://github.com/mouzt/mzt-biz-log/blob/07e2809ce894824ff435ebd50d53c5f3a9af045b/bizlog-sdk/src/main/java/com/mzt/logapi/starter/support/parse/LogFunctionParser.java#L21
这里value可能为null（变量未取到值），需增加value是否为空判断

**Comment by mouzt** [comment]
可以

**Comment by mouzt** [comment]
2.0.2 修复
