### ISSUE TITLE
LogRecord注解增加支持ElementType.TYPE

### ISSUE THREAD

**Issue by huntkalio** [mouzt/mzt-biz-log#58]
https://github.com/mouzt/mzt-biz-log/blob/07e2809ce894824ff435ebd50d53c5f3a9af045b/bizlog-sdk/src/main/java/com/mzt/logapi/starter/annotation/LogRecord.java#L9
这里是否考虑增加支持：ElementType.TYPE
让注解的一些默认值可以被替换。
类似spring boot的RequestMapping、PostMapping注解间的关系

**Comment by mouzt** [comment]
可以下个版本支持

**Comment by mouzt** [comment]
2.0.2 支持
