### ISSUE TITLE
springboot  不执行  日志保存方法

### ISSUE THREAD

**Issue by myy520** [mouzt/mzt-biz-log#59]
<img width="2164" alt="未命名鹅鹅鹅饿" src="https://user-images.githubusercontent.com/41657450/158945291-6167ec5c-43df-4424-acd8-91c8df84ac87.png">

**Comment by mouzt** [comment]
Springboot 启动类发一下 看看

**Comment by mouzt** [comment]
修复了 不加 @EnableTransactionManager 失效的问题
