### ISSUE TITLE
支持复杂对象变更记录嘛

### ISSUE THREAD

**Issue by eyon-org** [mouzt/mzt-biz-log#73]
支持复杂类型的数据变更日志嘛？

如下：
修改前：
{
    id: 1,
    name: "test",
   item: [
        {  projectid: 123, projectname: "测试项目" },
        {  projectid: 124, projectname: "测试项目" }
   ]
}

修改后：
{
    id: 1,
    name: "test1",
   item: [
        {  projectid: 123, projectname: "测试项目" },
        {  projectid: 124, projectname: "测试项目2" }
   ]
}

**Comment by mouzt** [comment]
DIff 功能可以支持，也可以字节写 function 函数
