### ISSUE TITLE
接口成功状态由返回值决定，怎么记录fail信息？

### ISSUE THREAD

**Issue by xtz136** [mouzt/mzt-biz-log#74]
你好，目前是接口抛出错误，才会记录fail信息。
当接口成功状态由返回值决定时，该怎么处理呢。

例如接口返回：{”code": 0}，当code等于0时表示成功，非0时表示失败。

我希望能自己判断接口是成功状态还是失败状态，或者有更好的实现方式。

**Comment by mouzt** [comment]
后面加个condition，目前只能通过异常判断

**Comment by mouzt** [comment]
3.0.1 已经支持
