### ISSUE TITLE
请问如果想添加自定义的通用属性应该是用什么方式？

### ISSUE THREAD

**Issue by AtomRun** [mouzt/mzt-biz-log#77]
假如需要记录IP的话，需要用什么方式？（例如要求记录用户每个操作时的IP地址），这种场景下是否有统一的地方写入LogRecordContext，然后SPEL能够直接拿到？不想每个操作都put一遍ip

**Comment by mouzt** [comment]
不需要，可以在自己实现的 ILogRecordService中获取当前用户上下文中的IP地址，保存就去就可以了，存库的实体可以自己扩展字段
