### ISSUE TITLE
大佬好，想咨询一下这里实现AOP的方式与基于注解实现的差异

### ISSUE THREAD

**Issue by lWoHvYe** [mouzt/mzt-biz-log#87]
之前一直是基于注解做AOP的，这种编程式应该会更灵活一些，除此之外还有什么考量吗。感谢

**Comment by sanliangitch** [comment]
没差异,在文章中提了一句,
基于注解的 AOP 在 Spring boot 1.5 中兼容性是有问题的，组件为了兼容 Spring boot1.5 的版本我们手工实现 Spring 的 AOP 逻辑

**Comment by lWoHvYe** [comment]
明白了，感谢大佬
