### ISSUE TITLE
新增一些操作人的额外信息

### ISSUE THREAD

**Issue by 648669556** [mouzt/mzt-biz-log#90]
我看目前
com.mzt.logapi.beans.LogRecord
关于操作者的信息只有 一个 用户id信息
private String operator;
能否提供一个字段存储关于用户的额外信息，这个额外信息可以由IOperatorGetService提供呢？

业务场景：在存储的时候需要同时存储操作者的一些额外信息

**Comment by sanliangitch** [comment]
有一个拓展字段不能满足你吗？

**Comment by 648669556** [comment]
目前看来，确实可以把很多东西都塞到拓展字段里面，用json序列化反序列化可以解决这一块的需求，但是感觉很困惑，操作用户相关的信息和业务相关的信息这样混杂在一起有点不够优雅。

**Comment by sanliangitch** [comment]
如果是你们项目全部都需要的话，可以数据库拓展字段，项目中的拓展字段全部给到用户了，至于怎样存储，可以不要那么死板。

**Comment by 648669556** [comment]
嗯，发现日志进行存储的时机在 上下文清除之前 ，也许这块内容也可以更加灵活的使用上下文处理

**Comment by 648669556** [comment]
麻烦大佬的解答啦，我这里的问题也解决了。后续有更加好用的功能和需求会继续提一些问题哦。🤪
